import BalanceCard from "@/components/user/dashboard/BalanceCard";
import DepositWithdrawActions from "@/components/user/dashboard/DepositWithAction";
import InvestmentForm from "@/components/user/dashboard/InvestmentForm";
import { getUserData } from "@/lib/actions/user.action";
import { formatPrice } from "@/lib/utils";

const DashboardOverview = async () => {
  const { data } = await getUserData();

  if (!data) return null;

  const { depositedBalance, investmentBalance, kycStatus } = data as UserExtra;

  const totalBalance = depositedBalance + investmentBalance;

  return (
    <div className="space-y-4">
      <h2 className="text-2xl font-bold text-white">Dashboard Overview</h2>

      {/* Total Balance Section */}
      <div className="bg-crypto-blue/60 border border-crypto-blue rounded-lg p-6 text-center">
        <h3 className="text-gray-400 text-sm">Total Balance</h3>
        <p className="text-3xl font-extrabold text-white mt-2">
          {formatPrice(totalBalance)}
        </p>
        <DepositWithdrawActions />
      </div>

      {/* Two-column Balances */}
      <div className="grid grid-cols-2 gap-4">
        <BalanceCard
          title="Investment Balance"
          amount={investmentBalance}
          subtitle="Earnings generated by AI investments"
        />
        <BalanceCard
          title="Available Balance"
          amount={depositedBalance}
          subtitle="Funds available for withdrawal or new investments"
        />
      </div>

      {/* AI Investment Form */}
      <InvestmentForm
        depositedBalance={depositedBalance}
        kycStatus={kycStatus}
      />
    </div>
  );
};

export default DashboardOverview;
