import BalanceCard from "@/components/user/dashboard/BalanceCard";
import DepositWithdrawActions from "@/components/user/dashboard/DepositWithAction";
import InvestmentForm from "@/components/user/dashboard/InvestmentForm";
import { getPortfolio } from "@/lib/actions/investment.action";
import { getUserData } from "@/lib/actions/user.action";
import { formatPrice } from "@/lib/utils";

const DashboardOverview = async () => {
  const { data: userData } = await getUserData();
  const { data: portfolioData } = await getPortfolio();

  if (!userData) return null;
  const { depositedBalance, kycStatus } = userData as UserExtra;

  const { totals = { activeProfit: 0 }, investments } = portfolioData || {};
  const totalBalance = depositedBalance + totals.activeProfit;
  const activeInvestmentPrincipals = investments?.reduce(
    (sum, i) => sum + (i.status === "active" ? i.principal : 0),
    0
  );

  return (
    <div className="space-y-4">
      <h2 className="text-2xl font-bold text-white">Dashboard Overview</h2>

      {/* Total Balance Section */}
      <div className="bg-crypto-blue/60 border border-crypto-blue rounded-lg p-6 text-center">
        <h3 className="text-gray-400 text-sm">Total Balance</h3>
        <p className="text-3xl font-extrabold text-white mt-2">
          {formatPrice(totalBalance)}
        </p>
        <DepositWithdrawActions />
      </div>

      {/* Two-column Balances */}
      <div className="grid grid-cols-2 gap-4">
        <BalanceCard
          title="Investment Balance"
          amount={totals.activeProfit}
          subtitle="Earnings generated by AI investments"
          activeInvestmentPrincipals={activeInvestmentPrincipals}
        />
        <BalanceCard
          title="Available Balance"
          amount={depositedBalance}
          subtitle="Funds available for withdrawal or new investments"
        />
      </div>

      {/* AI Investment Form */}
      <InvestmentForm
        depositedBalance={depositedBalance}
        kycStatus={kycStatus}
      />
    </div>
  );
};

export default DashboardOverview;
