"use client";

import BalanceCard from "@/components/protected/dashboard/BalanceCard";
import DepositWithdrawActions from "@/components/protected/dashboard/DepositWithAction";
import InvestmentForm from "@/components/protected/dashboard/InvestmentForm";

const DashboardOverview = () => {
  const balances = {
    total: 450000,
    investment: 320000,
    available: 130000,
  };

  return (
    <div className=" space-y-4">
      <h2 className="text-2xl font-bold text-white">Dashboard Overview</h2>

      {/* Total Balance Section */}
      <div className="bg-crypto-blue/60 border border-crypto-blue rounded-lg p-6 text-center">
        <h3 className="text-gray-400 text-sm">Total Balance</h3>
        <p className="text-3xl font-extrabold text-white mt-2">
          ${balances.total.toLocaleString()}
        </p>
        <DepositWithdrawActions />
      </div>

      {/* Two-column Balances */}
      <div className="grid grid-cols-2 gap-4">
        <BalanceCard
          title="Investment Balance"
          amount={balances.investment}
          subtitle="Earnings generated by AI investments"
        />
        <BalanceCard
          title="Available Balance"
          amount={balances.available}
          subtitle="Funds available for withdrawal or new investments"
        />
      </div>

      {/* AI Investment Form */}
      <InvestmentForm />
    </div>
  );
};

export default DashboardOverview;
