import { APP_NAME } from "@/lib/utils";

export const faqItems = [
  {
    question: `Is ${APP_NAME} free to use?`,
    answer: `${APP_NAME} is completely free to use. There are no subscription fees, setup charges, or hidden costs. You can create an account, invest, and withdraw your earnings at any time without paying platform fees.`,
  },
  {
    question: `Do I need trading experience to invest on ${APP_NAME}?`,
    answer: `No experience is required. ${APP_NAME} uses an advanced AI trading engine that handles market analysis, trade execution, and risk management automatically. You simply invest and the AI manages everything on your behalf.`,
  },
  {
    question: `Is investing with AI risky? What if the AI loses money?`,
    answer: `Every investment carries some level of risk, but our AI is trained with advanced algorithms designed to minimize loss and maximize gains. It constantly monitors the market and executes rapid trades to secure the best possible positions. Additionally, your daily return is protected — even if the AI underperforms on a given day, you still receive your fixed daily percentage.`,
  },
  {
    question: `If users earn a fixed percentage daily, how does ${APP_NAME} make money?`,
    answer: `${APP_NAME} earns from the extra profit generated by the AI. When the AI performs above the fixed daily return given to users, the additional profit is collected by the platform. This allows users to earn consistently while the company profits from AI overperformance. There are no hidden fees or surprise charges.`,
  },
  {
    question: `Is ${APP_NAME} available in my country?`,
    answer: `${APP_NAME} is accessible globally. You can invest from any country as long as you have a valid email address and an internet connection. There are no regional restrictions for creating an account or investing.`,
  },
  {
    question: `How long does it take to start earning?`,
    answer: `Earnings begin immediately after your investment is confirmed. Your daily return is automatically calculated and credited every 24 hours, without requiring any action from you.`,
  },
  {
    question: `What payment methods can I use to invest?`,
    answer: `${APP_NAME} supports multiple funding methods, including major cryptocurrencies such as USDT, BTC, ETH, and others. Deposits are processed quickly, allowing you to begin earning without delays. If you have any questions about supported payment methods, please contact our support team.`,
  },
  {
    question: `Can I withdraw my earnings anytime?`,
    answer: `Yes. You can withdraw both your earnings and your capital at any time. Withdrawals are processed promptly, and there are no penalties for withdrawing your funds.`,
  },
];
